version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://*:5000
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
